---
title: "Notes: Pouyet and Tregouet (2022) The Competitive Effects of Vertical Integration in Platform Markets"
author: "Yuki KAYABA"
date: "3/19/2023"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
output_dir: docs
bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# Summary of the Paper

（ひとことメモ）

- Platform Market（特にPCやスマホのOS市場）におけるVertical Integrationの影響について理論的に整理した論文
- Platform MarketはTwo-sided Market（Platformに対してApplication DeveloperとBuyerがいる）であり、ネットワーク効果も加味するとVertical Integrationが経済厚生に与える影響は複雑


## Motivation

- 

## Related Literature

- 

## Contribution

- 

# Details of the Paper

## Model

- See Figure 1 in the paper
- In this model, there are four types of players
  1. Platforms compete to license their operating systems to two manufacturers of devices
  2. Manufacturers equip their devices with an operating system, pay some fee to the corresponding platforms, and then compete to sell devices to buyers
  3. Developers pay fees to platforms to publish their applications on the operating systems
  4. Buyers decide which devices to buy, according to prices and applications available on the device
- $N + 1$ (with $N \geq 2$) platforms, denoted by $I, E_{1}, ..., E_{N} \in \mathcal{P}$
- Two manufacturers, denoted by $M_{1}$ and $M_{2}$

**Platforms**

- Platforms decide how the benefit from a buyer to share with manufacturers
  - Let $r$ be the per-user benefit generated by a buyer of a device equipped with an operating system
  - $\beta_{i}^{k} \in [0, 1]$ is the share of $r$ benefit kept by manufacturer $k$ (thus the share of the platform is $1 - \beta_{i}^{k}$)
- Platforms also charge fees to application developers
  - Denote by $a_{i}$ the fee charged by platform $i$ to allow a developer to make its application available on that platform’s operating system (can be either positive or negative)
- The profit of a platform $i \in P$ can be expressed as follows:

$$
\Pi_{i} = \sum_{k = 1, 2} \mathbf{1}_{ \{ M_{k} \text{ adopts } i \} } (1 - \beta_{i}^{k})rQ_{B}^{k} + a_{i}q_{i}
$$

**Manufacturers and Buyers**

- The number of buyers of manufacturer $M_{k}$’s device depends on the prices charged by manufacturers to buyers, denoted by $p_{k}$ and $p_{l}$, with $k \neq l \in \{ 1, 2 \}$, and on the number of applications running on the devices, denoted by $n_{S}^{k}$ and $n_{S}^{l}$
- Hence, it may be written as $Q_{B}^{k}(p_{k}, p_{l}, n_{S}^{k}, n_{S}^{l})$.
- The profit of a manufacturer $M_{k}$ when it chooses platform $i$’s operating system can thus be written as follows

$$
\pi_{k} = (p_{k} + \beta_{i}^{k}r)Q_{B}^{k}
$$

- From the buyer side, assume that:
  - devices are demand substitutes for buyers,or $\partial Q_{B}^{k} / \partial p_{k} < 0 < \partial Q_{B}^{k} / \partial p_{l}$
  - the direct price effect is stronger than the indirect one, or $\partial Q_{B}^{k} / \partial p_{k} + \partial Q_{B}^{k} / \partial p_{l} < 0$
  - buyers of device $k$ value positively the number of applications available on their devices, or $\partial Q_{B}^{k} / \partial n_{S}^{k} > 0$, but negatively the number of applications available on the other device, or $\partial Q_{B}^{k} / \partial n_{S}^{l} < 0$ 
- To compute the buyer surplus, we consider that there exists a representative buyer with utility function $U_{B}(q_{1}, q_{2}, n_{S}^{1}, n_{S}^{2})$ such that $Q_{B}^{1}$ and $Q_{B}^{2}$ are solutions of $\max_{(q_{1} \geq 0, q_{2} \geq 0)} U_{B}(q_{1}, q_{2} ,n_{S}^{1}, n_{S}^{2}) − p_{1}q_{1} − p_{2}q_{2}$. 
- Let $V_{B}(p_{1}, p_{2}, n_{S}^{1}, n_{S}^{2})$ denote the corresponding indirect utility

**Developers**

- Strictly increasing convex cost $C_{S}(q_{S})$ for a (representative) developer to develop $q_{S}$ applications 
- Once applications are developed, the developer bears the platform-specific cost $C_{i}(q_{i}) = c_{i}q_{i}$, with $c_{i} \geq 0$, to make $q_{i}$ applications available on platform $i$ (with $0 \leq q_{i} \leq q_{S}$)
- For the moment, assume that there are no porting costs for all platforms, or $c_{i} = 0$ for all $i \in \mathcal{P}$
- Assume that platforms set some developer fees $(a_{i})_{i \in P}$ 
- Let $n_{B}^{i}$ be the number of buyers using a device running platform $i$’s operating system
- When the developer creates $q_{S}$ applications and publishes $q_{i}$ of these on platform $i$, its profit is given by $\sum_{i \in \mathcal{P}} (u_{S} n_{B}^{i} q_{i} − a_{i}q_{i}) − C_{S}(q_{S})$, where $u_{S}$ relates to the strength of indirect network effects from the developer side of the market
- Since there are no porting costs, all applications are published on platform $i$ (that is, $q_{i} = q_{S}$) if $u_{S}n_{B}^{i} − a_{i} \geq 0$
- The net profit writes as follows

$$
q_{S} \sum_{i \in \mathcal{P}} (u_{S} n_{B}^{i} − a_{i}) \mathbf{1}_{ \{ u_{S}n_{B}^{i} - a_{i} \geq 0 \} } − C_{S}(q_{S})
$$

- Let $Q_{S}((n_{B}^{i}, a_{i})_{i \in \mathcal{P}})$ be the number of applications $q_{S}$ that maximizes the net profit and denote by $V_{S}((n_{B}^{i}, a_{i})_{i \in \mathcal{P}})$ the corresponding developer profit


**Timing**

1. In stage 1, platforms set the shares of the per-user benefit left to manufacturers in exchange of using their operating systems and the fees charged to developers
2. In stage 2, manufacturers choose the operating system for their devices
3. In stage 3, manufacturers set the prices of their devices in stage 3
4. In stage 4, buyers decide whether to buy a device, and, simultaneously, developers decide how much applications to develop and on which platforms to publish. 

- All decisions are public and we look for the subgame-perfect equilibrium of the game

### Stage 4: Participation Decisions

**Developers' Choices of Operating System**

- Note that any platform $i$ should never set a developer fee $a_{i}$ that discourages the developer from publishing on its operating system, for such strategy is weakly dominated by setting a zero fee
- Hence, we can consider without loss of generality that $u_{S}n_{B}^{i} - a_{i} \geq 0$ for any platform $i \in \mathcal{P}$
- Therefore, the representative developer is willing to publish all its applications on all the platforms (that is, $q_{i} = q_{S}$ for all $i \in \mathcal{P}$).
- The developer’s profit can thus be rewritten more simply as $(u_{S} (n_{B}^{1} + n_{B}^{2}) − a)q_{S} − C_{S}(q_{S})$ where $a \equiv \sum_{i \in \mathcal{P}} a_{i}$ denotes the ‘total developer fee’
- The number of applications $n_{S}$ that maximizes this profit is given by $n_{S} = Q_{S}(u_{S}(n_{B}^{1} + n_{B}^{2}) − a)$, where $Q_{S} = (C′_{S})^{-1}$
- Another immediate consequence of the fact that $u_{S} n_{B}^{i} − a_{i} \geq 0$ for any platform $i$ is that whatever their choices of operating systems, manufacturers benefit from the same number of applications running on their devices: $n_{S}^{1} = n_{S}^{2} \equiv n_{S}$
- The demand for device $k$ may now be written more simply as $n_{B}^{k} = Q_{B}^{k}(p_{k}, p_{l}, n_{S})$


**Buyers' and Developers' Participation Decisions**

- The number of buyers of each device and the number of applications must be consistent with each other and solve:

$$
\begin{align}
n_{B}^{1} &= Q_{B}^{1} (p_{1}, p_{2} ,n_{S}) \\
n_{B}^{2} &= Q_{B}^{2} (p_{2}, p_{1} ,n_{S}) \\
n_{S} &= Q_{S}(u_{S}(n_{B}^{1} + n_{B}^{2}) − a) \\
\end{align}
$$

- Assume that the solution is unique and interior for the relevant range of prices
- That solution defines the buyers’ demands for devices, denoted by $D_{k}(p_{k}, p_{l}, a)$ with $k \neq l \in \{ 1, 2 \}$, and the number of applications developed (also called the developers’ demand), denoted by $D_{S}(p_{1}, p_{2}, a)$
- The following usual properties hold: 
  - $\partial D_{S} / \partial p_{k} < 0$ and $\partial D_{S} / \partial a < 0$
  - $\partial D_{k} / \partial p_{k} < 0$ and $\partial D_{k} / \partial a < 0$
- We further impose that $\partial D_{k} / \partial p_{k} + \partial D_{k} / \partial p_{l} < 0$

**Impact of Networks Effects on Product Market Interactions**

- The demand faced by a manufacturer may, indeed, either increase or decrease with the price of the rival manufacturer, depending on the strength of indirect network effects relative to the degree of product market competition
- It follows that:

$$
\frac{\partial D_{k}}{\partial p_{l}} = \frac{\partial Q_{B}^{k}}{\partial p_{l}} + \frac{\partial Q_{B}^{k}}{\partial n_{S}}\frac{\partial D_{S}}{\partial p_{l}}
$$
which can be positive or negative

- The intuition is as follows
  - If $p_{l}$ increases, then some buyers are diverted from $M_{l}$, and $M_{k}$’s demand increases by $\partial Q_{B}^{k} / \partial p_{l}$
  - The increase in $p_{l}$ has, moreover, a negative impact on the total number of buyers, since the direct price effect on buyers of device $l$ is stronger than the indirect price effect on buyers of device $k$ ($\partial Q_{B}^{l} / \partial p_{l} + \partial Q_{B}^{k} / \partial p_{l} < 0$)
  - Since there are less buyers overall, there are fewer applications too, for developers find it less attractive to develop ($\partial D_{S} / \partial p_{l} < 0$)
  - Because buyers value applications, this negatively affects $M_{k}$’s demand by $\partial Q_{B}^{k} / \partial n_{S}$
- We therefore expect that:
  - When indirect network effects are small, the rivalry effect created by product market competition dominates and $\partial D_{k} / \partial p_{l} \geq 0$, that is, devices are demand substitutes
  - When product market competition is weak, then the interaction created by indirect network effects dominates and $\partial D_{k} / \partial p_{l} \leq 0$, that is, devices are demand complements
- In the sequel, we shall focus on the case studied by the bulk of the literature on strategic vertical integration, namely the case where manufacturers’ products are demand substitutes:

<u>Assumption 1</u>

*Indirect network effects are not too strong relative to product market competition so that manufacturers’ products are demand substitutes: for $k \neq l$, for all $(p_{k}, p_{l}, a)$*

$$
\frac{\partial D_{k}}{\partial p_{l}} (p_{k}, p_{l}, a) \geq 0
$$

### Stage 3: Competition between Manufacturers

- 次回ここから





